apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
spec:
  type: NodePort
  selector:
    app: haproxy
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: stats
      port: 8404
      targetPort: 8404
      nodePort: 30404
