apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: amf-service-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: amf-service
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
