apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcrf-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcrf-service
  template:
    metadata:
      labels:
        app: pcrf-service
    spec:
      containers:
      - name: pcrf-service
        image: pcrf-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081

        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
