apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smsc-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: smsc
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
