apiVersion: v1
kind: Service
metadata:
  name: smsc-service
  labels:
    app: smsc
spec:
  selector:
    app: smsc
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8001
      targetPort: 8001
  type: ClusterIP
